In [4]:
from datasets.dataloader import getdataloader
import torch
data = getdataloader("mosei", 8, '')[0]

Input feature wav2vec-large-c-UTT ===> dim is 512; No. sample is 22856
Input feature deberta-large-4-UTT ===> dim is 1024; No. sample is 22856
Input feature manet_UTT ===> dim is 1024; No. sample is 22856


In [5]:
train_data = data['train']

In [3]:
from models.msamodel import MSAModel
import torch

model = model = MSAModel(2, [512, 1024, 1024], 512, 4, 4)


In [6]:
itr = iter(train_data)
a, t, v, y, l = next(itr)

tensor([25], dtype=torch.int32)
tensor([1], dtype=torch.int32)
tensor([3], dtype=torch.int32)
tensor([8], dtype=torch.int32)
tensor([2], dtype=torch.int32)
tensor([11], dtype=torch.int32)
tensor([5], dtype=torch.int32)
tensor([3], dtype=torch.int32)


In [19]:
from torch.nn.utils.rnn import unpad_sequence

eval_attr = torch.concat(unpad_sequence(y, l, batch_first=True)).long()
print(eval_attr.shape)

torch.Size([58])


In [20]:
out, _, _ = model([a, t, v],l)
out.shape

torch.Size([58, 2])

In [22]:
from torch.nn import functional as F
loss = F.cross_entropy(out, eval_attr)
loss

tensor(1.1234, grad_fn=<NllLossBackward0>)

In [2]:
from transformers import ASTForAudioClassification
encoder_0 = ASTForAudioClassification.from_pretrained("MIT/ast-finetuned-audioset-10-10-0.4593")
encoder_0

ASTForAudioClassification(
  (audio_spectrogram_transformer): ASTModel(
    (embeddings): ASTEmbeddings(
      (patch_embeddings): ASTPatchEmbeddings(
        (projection): Conv2d(1, 768, kernel_size=(16, 16), stride=(10, 10))
      )
      (dropout): Dropout(p=0.0, inplace=False)
    )
    (encoder): ASTEncoder(
      (layer): ModuleList(
        (0-11): 12 x ASTLayer(
          (attention): ASTAttention(
            (attention): ASTSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
            )
            (output): ASTSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.0, inplace=False)
            )
          )
          (intermediate): ASTIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=T